name: wgscraper
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - cookiecutter
  - git
  - pandas
  - beautifulsoup4
  - requests
  - sphinx
  - coverage
  - flake8
  - python-dotenv[version='>=0.5.1']
  - jupyter
  - selenium
  - jupyterlab
  - loguru
  - dateparser
  - nodejs
  - matplotlib
  - setuptools
  - wheel
  - twine


